package driver

import (
	"archive/zip"
	"os"
	"path/filepath"
	"testing"
)

// writeTestMacZip creates a .zip at zipPath containing the given entries
// (name -> content), built in-memory - avoids committing an actual binary
// .zip/.dmg fixture to the repo, mirroring zip_test.go's own
// writeTestZip helper.
func writeTestMacZip(t *testing.T, zipPath string, entries map[string]string) {
	t.Helper()
	f, err := os.Create(zipPath)
	if err != nil {
		t.Fatalf("creating %s: %v", zipPath, err)
	}
	defer f.Close()

	zw := zip.NewWriter(f)
	for name, content := range entries {
		w, err := zw.Create(name)
		if err != nil {
			t.Fatalf("adding %s to zip: %v", name, err)
		}
		if _, err := w.Write([]byte(content)); err != nil {
			t.Fatalf("writing zip entry %s: %v", name, err)
		}
	}
	if err := zw.Close(); err != nil {
		t.Fatalf("closing zip: %v", err)
	}
}

// TestBuildMacCatalog_RecordsZipWithoutExtracting is the direct regression
// test for GitHub issue #11: a .zip found under a manufacturer folder is
// recorded as its own MacPackageZip entry - not extracted at catalog-build
// time at all, and critically, no permanent sibling folder is created on
// disk (the real, repeatedly-confirmed-live bug: ~2.6G/36 folders on a real
// machine, regenerated by every catalog build before this fix).
func TestBuildMacCatalog_RecordsZipWithoutExtracting(t *testing.T) {
	root := t.TempDir()
	canonDir := filepath.Join(root, "macOS", "Canon", "15-Sequoia")
	if err := os.MkdirAll(canonDir, 0o755); err != nil {
		t.Fatal(err)
	}
	zipPath := filepath.Join(canonDir, "UFRII_v10.19.25_mac.zip")
	writeTestMacZip(t, zipPath, map[string]string{
		"UFRII_v10.19.25_mac.dmg": "pretend this is a real disk image",
	})

	cat, err := BuildMacCatalog(root)
	if err != nil {
		t.Fatalf("BuildMacCatalog: %v", err)
	}

	pkgs := cat.Packages["Canon"]
	if len(pkgs) != 1 {
		t.Fatalf("expected exactly 1 Canon package (the .zip itself), got %d: %v", len(pkgs), pkgs)
	}
	if pkgs[0].Path != zipPath {
		t.Errorf("expected the package's own Path to be the .zip itself (%s), got %q", zipPath, pkgs[0].Path)
	}
	if pkgs[0].Kind != MacPackageZip {
		t.Errorf("expected Kind=MacPackageZip, got %v", pkgs[0].Kind)
	}

	extractedDir := filepath.Join(canonDir, "UFRII_v10.19.25_mac")
	if _, err := os.Stat(extractedDir); !os.IsNotExist(err) {
		t.Errorf("expected no permanent sibling folder to be created for the .zip, but %s exists", extractedDir)
	}
}

// TestBuildMacCatalog_CleansUpLeftoverExtractedSiblingFolder guards the
// transition case: a folder left behind by the OLD eager-extraction
// behavior (or any earlier PDT version) sitting next to its own .zip must
// be recognized and removed, not left to sit there forever *and* not
// double-counted alongside the .zip's own new MacPackageZip entry.
func TestBuildMacCatalog_CleansUpLeftoverExtractedSiblingFolder(t *testing.T) {
	root := t.TempDir()
	canonDir := filepath.Join(root, "macOS", "Canon", "15-Sequoia")
	if err := os.MkdirAll(canonDir, 0o755); err != nil {
		t.Fatal(err)
	}
	zipPath := filepath.Join(canonDir, "UFRII_v10.19.25_mac.zip")
	writeTestMacZip(t, zipPath, map[string]string{
		"UFRII_v10.19.25_mac.dmg": "pretend this is a real disk image",
	})

	leftoverDir := filepath.Join(canonDir, "UFRII_v10.19.25_mac")
	leftoverFile := filepath.Join(leftoverDir, "UFRII_v10.19.25_mac.dmg")
	if err := os.MkdirAll(leftoverDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(leftoverFile, []byte("leftover from a pre-fix catalog build"), 0o644); err != nil {
		t.Fatal(err)
	}

	cat, err := BuildMacCatalog(root)
	if err != nil {
		t.Fatalf("BuildMacCatalog: %v", err)
	}

	pkgs := cat.Packages["Canon"]
	if len(pkgs) != 1 {
		t.Fatalf("expected exactly 1 Canon package (the .zip; the leftover folder must not be double-counted), got %d: %v", len(pkgs), pkgs)
	}
	if pkgs[0].Path != zipPath {
		t.Errorf("expected the package to be the .zip itself, got %q", pkgs[0].Path)
	}
	if _, err := os.Stat(leftoverDir); !os.IsNotExist(err) {
		t.Errorf("expected the leftover extracted folder to be removed, but %s still exists", leftoverDir)
	}
}

// TestResolveMacZipSource_PassthroughForNonZip guards the common case
// (every manufacturer whose real download ships as a .dmg/.pkg/.dmg.gz
// directly, no zip wrapper at all) - resolveMacZipSource must be a pure
// no-op for anything that isn't a .zip.
func TestResolveMacZipSource_PassthroughForNonZip(t *testing.T) {
	dmgPath := filepath.Join(t.TempDir(), "real.dmg")
	realPath, cleanup, err := resolveMacZipSource(dmgPath)
	defer cleanup()
	if err != nil {
		t.Fatalf("resolveMacZipSource: %v", err)
	}
	if realPath != dmgPath {
		t.Errorf("expected pass-through of %q, got %q", dmgPath, realPath)
	}
}

// TestResolveMacZipSource_ExtractsZippedDmgAndIgnoresAppleDoubleJunk mirrors
// a real Canon macOS driver download exactly: a .zip directly wrapping one
// .dmg, plus the __MACOSX/._<name> AppleDouble resource-fork stub macOS's
// own Archive Utility adds when zipping something on a Mac - confirmed live
// that stub shares the real file's own ".dmg" extension, so without
// findFirstByExt's own __MACOSX/"._" filtering, this could resolve to a
// second, bogus ~300-byte stub instead of the real 80+ MB one. Also
// confirms cleanup actually removes the temp directory this creates.
func TestResolveMacZipSource_ExtractsZippedDmgAndIgnoresAppleDoubleJunk(t *testing.T) {
	zipPath := filepath.Join(t.TempDir(), "UFRII_v10.19.25_mac.zip")
	writeTestMacZip(t, zipPath, map[string]string{
		"UFRII_v10.19.25_mac.dmg":            "pretend this is a real disk image",
		"__MACOSX/._UFRII_v10.19.25_mac.dmg": "AppleDouble resource-fork junk, not a real disk image",
	})

	realPath, cleanup, err := resolveMacZipSource(zipPath)
	if err != nil {
		t.Fatalf("resolveMacZipSource: %v", err)
	}
	if filepath.Base(realPath) != "UFRII_v10.19.25_mac.dmg" {
		t.Errorf("expected the real UFRII_v10.19.25_mac.dmg, got %q", realPath)
	}
	data, err := os.ReadFile(realPath)
	if err != nil || string(data) != "pretend this is a real disk image" {
		t.Errorf("expected the real .dmg's own content, got data=%q err=%v", data, err)
	}
	tmpParent := filepath.Dir(realPath)
	cleanup()
	if _, err := os.Stat(tmpParent); !os.IsNotExist(err) {
		t.Errorf("expected cleanup to remove the temp extraction directory %s, but it still exists", tmpParent)
	}
}

// TestResolveMacZipSource_ResolvesNestedZipInsideZip guards the real,
// confirmed-live shape (2026-09-13) a Konica Minolta download needs: a .zip
// wraps two region subfolders, each holding its own *inner* zip wrapping the
// real .pkg - two levels of zip nesting, not the one level Canon's own shape
// needs. A single extraction pass only sees .zip files that already exist
// before it starts, so the inner zip (only created *by* that same pass's own
// extraction of the outer zip) would otherwise never be discovered at all -
// resolveMacZipSource repeats passes against its own temp directory until
// one finds nothing new to extract.
func TestResolveMacZipSource_ResolvesNestedZipInsideZip(t *testing.T) {
	innerZipPath := filepath.Join(t.TempDir(), "inner.pkg.zip")
	writeTestMacZip(t, innerZipPath, map[string]string{
		"real.pkg": "pretend this is a real installer package",
	})
	innerZipBytes, err := os.ReadFile(innerZipPath)
	if err != nil {
		t.Fatal(err)
	}

	outerZipPath := filepath.Join(t.TempDir(), "C750i_Series_MacOS_v5.2.14A.zip")
	writeTestMacZip(t, outerZipPath, map[string]string{
		"C750i_Series_MacOS_v5.2.14A/WW_Letter/inner.pkg.zip": string(innerZipBytes),
	})

	realPath, cleanup, err := resolveMacZipSource(outerZipPath)
	defer cleanup()
	if err != nil {
		t.Fatalf("resolveMacZipSource: %v", err)
	}
	if filepath.Base(realPath) != "real.pkg" {
		t.Errorf("expected the real nested real.pkg, got %q", realPath)
	}
}

// TestResolveMacZipSource_ErrorsWhenNothingRecognizedInside guards the
// no-.dmg/.pkg-found case (a corrupt or genuinely unrelated .zip) reports a
// real error rather than silently returning an empty/invalid path, and that
// its own temp directory is still cleaned up rather than leaked.
func TestResolveMacZipSource_ErrorsWhenNothingRecognizedInside(t *testing.T) {
	zipPath := filepath.Join(t.TempDir(), "unrelated.zip")
	writeTestMacZip(t, zipPath, map[string]string{
		"readme.txt": "nothing installable in here",
	})

	_, cleanup, err := resolveMacZipSource(zipPath)
	defer cleanup()
	if err == nil {
		t.Error("expected an error when no .dmg/.pkg is found inside the zip")
	}
}
