// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {printer} from '../models';
import {config} from '../models';

export function AllManufacturers():Promise<Array<string>>;

export function CheckExportCollisions(arg1:string,arg2:string):Promise<main.ExportCollisionResult>;

export function DefaultDriverFor(arg1:string):Promise<string>;

export function Deploy(arg1:Array<printer.PrinterRow>,arg2:string,arg3:string):Promise<Array<main.DeployRowResult>>;

export function DriverCandidates(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function ExportConfigs(arg1:string,arg2:string,arg3:string):Promise<main.ExportResult>;

export function ForceQuit():Promise<void>;

export function FormatDrives(arg1:Array<string>):Promise<main.BatchDriveResult>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCatalogStatus():Promise<main.CatalogStatus>;

export function GetSettings():Promise<main.Settings>;

export function ImportCsv():Promise<main.ImportResult>;

export function IsRunningFromRemovableDrive():Promise<boolean>;

export function ListPreinstallFolders(arg1:string):Promise<main.PreinstallFoldersResult>;

export function ListRemovableDrives():Promise<main.ListDrivesResult>;

export function Manufacturers():Promise<Array<string>>;

export function NewCsvTemplate():Promise<main.PathResult>;

export function OpenConfiguration():Promise<main.OpenConfigResult>;

export function OpenDriversBasePathInExplorer(arg1:string):Promise<main.OpenFolderResult>;

export function OpenManufacturerURL(arg1:string):Promise<void>;

export function OpenRepoURL():Promise<void>;

export function PickFolder(arg1:string):Promise<main.PathResult>;

export function Platform():Promise<string>;

export function RefreshDriverCatalog():Promise<main.CatalogStatus>;

export function SaveConfiguration(arg1:config.SavedConfig):Promise<main.PathResult>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function StopDeploy():Promise<void>;

export function SyncDriversToFlashDrives(arg1:Array<string>):Promise<main.BatchDriveResult>;

export function WritePortablePDT(arg1:Array<string>):Promise<main.BatchDriveResult>;
