// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyUpdate(arg1) {
  return window['go']['main']['App']['ApplyUpdate'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function DefaultDriverFor(arg1) {
  return window['go']['main']['App']['DefaultDriverFor'](arg1);
}

export function Deploy(arg1, arg2, arg3) {
  return window['go']['main']['App']['Deploy'](arg1, arg2, arg3);
}

export function DriverCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['DriverCandidates'](arg1, arg2, arg3);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCatalogStatus() {
  return window['go']['main']['App']['GetCatalogStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportCsv() {
  return window['go']['main']['App']['ImportCsv']();
}

export function Manufacturers() {
  return window['go']['main']['App']['Manufacturers']();
}

export function Models(arg1) {
  return window['go']['main']['App']['Models'](arg1);
}

export function NewCsvTemplate() {
  return window['go']['main']['App']['NewCsvTemplate']();
}

export function OpenConfiguration() {
  return window['go']['main']['App']['OpenConfiguration']();
}

export function OpenManufacturerURL(arg1) {
  return window['go']['main']['App']['OpenManufacturerURL'](arg1);
}

export function OpenRepoURL() {
  return window['go']['main']['App']['OpenRepoURL']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
