// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AllManufacturers() {
  return window['go']['main']['App']['AllManufacturers']();
}

export function CheckExportCollisions(arg1, arg2) {
  return window['go']['main']['App']['CheckExportCollisions'](arg1, arg2);
}

export function DefaultDriverFor(arg1) {
  return window['go']['main']['App']['DefaultDriverFor'](arg1);
}

export function Deploy(arg1, arg2, arg3) {
  return window['go']['main']['App']['Deploy'](arg1, arg2, arg3);
}

export function DriverCandidates(arg1, arg2, arg3) {
  return window['go']['main']['App']['DriverCandidates'](arg1, arg2, arg3);
}

export function ExportConfigs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportConfigs'](arg1, arg2, arg3);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function FormatDrives(arg1) {
  return window['go']['main']['App']['FormatDrives'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCatalogStatus() {
  return window['go']['main']['App']['GetCatalogStatus']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportCsv() {
  return window['go']['main']['App']['ImportCsv']();
}

export function IsRunningFromRemovableDrive() {
  return window['go']['main']['App']['IsRunningFromRemovableDrive']();
}

export function ListPreinstallFolders(arg1) {
  return window['go']['main']['App']['ListPreinstallFolders'](arg1);
}

export function ListRemovableDrives() {
  return window['go']['main']['App']['ListRemovableDrives']();
}

export function MacModelManufacturers() {
  return window['go']['main']['App']['MacModelManufacturers']();
}

export function Manufacturers() {
  return window['go']['main']['App']['Manufacturers']();
}

export function Models(arg1, arg2) {
  return window['go']['main']['App']['Models'](arg1, arg2);
}

export function NewCsvTemplate() {
  return window['go']['main']['App']['NewCsvTemplate']();
}

export function OpenConfiguration() {
  return window['go']['main']['App']['OpenConfiguration']();
}

export function OpenDriversBasePathInExplorer(arg1) {
  return window['go']['main']['App']['OpenDriversBasePathInExplorer'](arg1);
}

export function OpenManufacturerURL(arg1) {
  return window['go']['main']['App']['OpenManufacturerURL'](arg1);
}

export function OpenRepoURL() {
  return window['go']['main']['App']['OpenRepoURL']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function Platform() {
  return window['go']['main']['App']['Platform']();
}

export function RefreshDriverCatalog() {
  return window['go']['main']['App']['RefreshDriverCatalog']();
}

export function ResetConfigPath() {
  return window['go']['main']['App']['ResetConfigPath']();
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StopDeploy() {
  return window['go']['main']['App']['StopDeploy']();
}

export function SyncDriversToFlashDrives(arg1) {
  return window['go']['main']['App']['SyncDriversToFlashDrives'](arg1);
}

export function WritePortablePDT(arg1) {
  return window['go']['main']['App']['WritePortablePDT'](arg1);
}
